version: '3.6'

services:
  blackbox:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/blackbox
      context: ..
      dockerfile: docker/blackbox/Dockerfile
    image: ${DOCKER_REPOSITORY}/blackbox:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_9115_NAME=${COMPOSE_SERVICE_NAME}-blackbox-9115
    - SERVICE_9115_CHECK_TCP=true
    - SERVICE_9115_CHECK_INITIAL_STATUS=passing
    - SERVICE_9115_TAGS=${BLACKBOX_SERVICE_9115_TAGS}
    networks:
    - private
    - public
    ports:
    - 9115
    restart: always

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
  public:
    external: true
    name: node
