version: '3.6'

services:
  prometheus:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/prometheus
      - MONITORING_PRIMARY_TARGETS_BLACKBOX=${PROMETHEUS_MONITORING_PRIMARY_TARGETS_BLACKBOX}
      - MONITORING_SECONDARY_TARGETS_BLACKBOX=${PROMETHEUS_MONITORING_SECONDARY_TARGETS_BLACKBOX}
      context: ../..
      dockerfile: docker/prometheus/Dockerfile
    image: ${DOCKER_REPOSITORY}/prometheus:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_9090_NAME=${COMPOSE_SERVICE_NAME}-prometheus-9090
    - SERVICE_9090_CHECK_TCP=true
    - SERVICE_9090_CHECK_INITIAL_STATUS=passing
    - SERVICE_9090_TAGS=${PROMETHEUS_SERVICE_9090_TAGS}
    networks:
    - private
    - public
    ports:
    - 9090
    restart: always
    volumes:
    - prometheus:/prometheus

volumes:
  prometheus:

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
  public:
    external: true
    name: node
