---
# file: tasks/main.yml

- import_tasks: vars.yml
  tags:
    - vars
- import_tasks: packages.yml
  tags:
    - packages
- import_tasks: ssh.yml
  tags:
    - ssh
- import_tasks: files.yml
  tags:
    - files
- import_tasks: git.yml
  tags:
    - git
- import_tasks: service.yml
  tags:
    - service
- import_tasks: user.yml
  tags:
    - user
