---
# file: tasks/service.yml

- name: service - activate local (openrc)
  service:
    name: local
    enabled: yes
  when: hosts_enable_local and ansible_service_mgr|lower == "openrc"
  become: yes

- name: service - activate zram
  service:
    name: zram
    state: started
    enabled: yes
  when: hosts_enable_zram and ansible_service_mgr|lower != "openrc"
  become: yes

- name: service - activate zram (openrc)
  service:
    name: zram-openrc
    state: started
    enabled: yes
    runlevel: boot
  when: hosts_enable_zram and ansible_service_mgr|lower == "openrc"
  become: yes
