version: '3.6'

services:
  grafana:
    build:
      args:
      - AWS_ACCESS_KEY=${GRAFANA_AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${GRAFANA_AWS_SECRET_KEY}
      - DOCKER_BUILD_DIR=docker/grafana
      - MYSQL_GRAFANA_DB=${GRAFANA_MYSQL_DB}
      - MYSQL_GRAFANA_PASSWORD=${GRAFANA_MYSQL_PASSWORD}
      - MYSQL_GRAFANA_USER=${GRAFANA_MYSQL_USER}
      context:  ..
      dockerfile: docker/grafana/Dockerfile
    environment:
    - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    image: ${DOCKER_REPOSITORY}/grafana:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_3000_NAME=${COMPOSE_SERVICE_NAME}-grafana-3000
    - SERVICE_3000_CHECK_TCP=true
    - SERVICE_3000_CHECK_INITIAL_STATUS=passing
    - SERVICE_3000_TAGS=${GRAFANA_SERVICE_3000_TAGS}
    networks:
    - private
    - public
    ports:
    - 3000
    restart: always
    volumes:
    - grafana:/var/lib/grafana

volumes:
  grafana:

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
  public:
    external: true
    name: node
